name: build, lint, test, deploy
on: push
jobs:
  build-lint-test:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.6.0
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Set NODE_ENV
        run: export NODE_ENV=local
      - name: Run tests
        run: npm test       
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: samc621/sneakerbot
          tag_with_ref: true